version: '3'

services:
  nestjs:
    build:
      context: .
      target: development
    image: nestjs
    container_name: companies
    command: npm run start:debug
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - services_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - services_network

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4572:4572"
      - "4576:4576"
    environment:
      - SERVICES=s3,sqs
      - IMAGE_NAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_DEFAULT_OUTPUT=json
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - services_network

networks:
  services_network:
    external: true