version: '3'
services:
  # laravel:
  #   build: .
  #   container_name: laravel
  #   ports:
  #     - 8080:8000
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - services_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - services_network

networks:
  services_network:
    external: true